In [1]:
import glob
import pandas as pd

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
all_filenames

['cleased_2018_05.csv', 'cleased_2018_04.csv', 'cleased_2018_03.csv']

In [4]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "pj2_combined.csv", index=False, encoding='utf-8-sig')

In [7]:
combined_csv

,VendorID,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,tip_amount,total_amount,year,month,day,weekday,hour,weather,hour_interval
0,1,2018-03-22 11:56:30,2018-03-22 12:00:22,1,0.50,1,239,238,1,4.5,0.0,1.06,6.36,2018,3,22,3,11,overcast,9am-11am
1,1,2018-03-01 18:15:38,2018-03-01 18:30:17,1,2.40,1,140,239,1,11.5,1.0,2.66,15.96,2018,3,1,3,18,sunny,6pm-8pm
2,1,2018-03-27 21:32:47,2018-03-27 21:51:33,1,1.90,1,163,164,1,13.0,0.5,2.85,17.15,2018,3,27,1,21,overcast,9pm-11pm
3,1,2018-03-04 03:41:53,2018-03-04 03:48:37,1,2.20,1,226,82,2,9.0,0.5,0.00,10.30,2018,3,4,6,3,sunny,3am-5am
4,2,2018-03-01 12:05:29,2018-03-01 12:22:50,3,1.71,1,164,237,1,11.5,0.0,2.46,14.76,2018,3,1,3,12,sunny,12pm-2pm
5,2,2018-03-24 13:41:54,2018-03-24 14:09:47,1,4.32,1,161,112,1,21.0,0.0,4.36,26.16,2018,3,24,5,13,sunny,12pm-2pm
6,1,2018-03-27 14:20:03,2018-03-27 14:29:26,4,1.30,1,140,236,1,8.0,0.0,1.75,10.55,2018,3,27,1,14,overcast,12pm-2pm
7,1,2018-03-17 20:42:01,2018-03-17 20:46:01,1,0.40,1,90,68,2,4.5,0.5,0.00,5.80,2018,3,17,5,20,rainy,6pm-8pm
8,1,2018-03-05 20:58:37,2018-03-05 21:07:36,1,1.50,1,142,141,1,8.5,0.5,1.95,11.75,2018,3,5,0,20,sunny,6pm-8pm
9,1,2018-03-28 23:15:03,2018-03-28 23:21:21,2,1.30,1,233,170,1,7.0,0.5,1.65,9.95,2018,3,28,2,23,overcast,9pm-11pm
10,1,2018-03-03 20:46:49,2018-03-03 21:01:43,2,1.50,1,249,79,1,10.5,0.5,2.35,14.15,2018,3,3,5,20,sunny,6pm-8pm
11,1,2018-03-02 18:43:30,2018-03-02 18:47:15,2,0.70,1,263,236,1,4.5,1.0,1.00,7.30,2018,3,2,4,18,sunny,6pm-8pm
12,2,2018-03-29 19:38:42,2018-03-29 20:02:48,2,5.89,1,100,256,1,21.5,1.0,5.82,29.12,2018,3,29,3,19,sunny,6pm-8pm
13,1,2018-03-31 23:34:38,2018-03-31 23:42:48,1,1.50,1,261,114,2,7.5,0.5,0.00,8.80,2018,3,31,5,23,overcast,9pm-11pm
14,2,2018-03-29 17:34:57,2018-03-29 17:39:17,1,0.72,1,263,263,1,5.0,1.0,1.36,8.16,2018,3,29,3,17,sunny,3pm-5pm
15,2,2018-03-13 19:33:09,2018-03-13 19:41:28,1,1.53,1,161,170,1,7.5,1.0,1.86,11.16,2018,3,13,1,19,rainy,6pm-8pm
16,2,2018-03-19 18:52:54,2018-03-19 18:59:37,1,0.83,1,236,236,1,6.5,1.0,1.66,9.96,2018,3,19,0,18,rainy,6pm-8pm
17,2,2018-03-09 18:08:21,2018-03-09 18:11:01,4,0.55,1,162,162,1,4.0,1.0,0.00,5.80,2018,3,9,4,18,sunny,6pm-8pm
18,1,2018-03-14 10:37:13,2018-03-14 10:54:38,1,2.60,1,140,239,1,13.0,0.0,3.45,17.25,2018,3,14,2,10,sunny,9am-11am
19,1,2018-03-06 14:26:16,2018-03-06 14:34:11,1,0.80,1,144,231,1,6.5,0.0,1.45,8.75,2018,3,6,1,14,overcast,12pm-2pm
20,2,2018-03-20 19:45:32,2018-03-20 19:46:48,2,0.52,1,263,236,2,3.5,1.0,0.00,5.30,2018,3,20,1,19,overcast,6pm-8pm
21,2,2018-03-04 14:53:43,2018-03-04 15:01:15,1,1.35,1,264,264,2,7.0,0.0,0.00,7.80,2018,3,4,6,14,sunny,12pm-2pm
22,2,2018-03-31 00:45:30,2018-03-31 00:54:23,2,1.77,1,24,239,2,9.0,0.5,0.00,10.30,2018,3,31,5,0,overcast,0am-2am
23,2,2018-03-22 16:04:01,2018-03-22 16:11:20,1,0.46,1,164,186,1,6.0,1.0,1.95,9.75,2018,3,22,3,16,overcast,3pm-5pm
24,2,2018-03-18 11:23:27,2018-03-18 11:48:18,1,7.84,1,230,13,1,26.5,0.0,6.82,34.12,2018,3,18,6,11,overcast,9am-11am
25,1,2018-03-26 22:35:00,2018-03-26 22:37:30,1,0.50,1,24,151,1,4.0,0.5,1.05,6.35,2018,3,26,0,22,sunny,9pm-11pm
26,2,2018-03-28 21:05:31,2018-03-28 21:17:21,1,1.63,1,249,68,1,9.5,0.5,2.16,12.96,2018,3,28,2,21,overcast,9pm-11pm
27,2,2018-03-09 03:58:06,2018-03-09 04:01:27,6,0.61,1,79,224,2,4.5,0.5,0.00,5.80,2018,3,9,4,3,sunny,3am-5am
28,1,2018-03-16 02:45:46,2018-03-16 03:08:49,1,12.40,1,144,134,1,35.5,0.5,7.35,44.15,2018,3,16,4,2,rainy,0am-2am
29,2,2018-03-31 20:15:43,2018-03-31 20:25:18,5,1.40,1,234,230,2,8.0,0.5,0.00,9.30,2018,3,31,5,20,overcast,6pm-8pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902873,2,2018-05-21 20:53:09,2018-05-21 20:55:57,2,1.09,1,229,170,1,5.0,0.5,1.26,7.56,2018,5,21,0,20,snow,6pm-8pm
902874,2,2018-05-01 17:02:21,2018-05-01 17:32:14,1,5.30,1,170,260,1,22.5,1.0,3.00,33.06,2018,5,1,1,17,sunny,3pm-5pm
902875,2,2018-05-18 14:22:49,2018-05-18 14:26:18,1,0.28,1,236,263,1,4.0,0.0,1.00,5.80,2018,5,18,4,14,sunny,12pm-2pm
902876,1,2018-05-31 20:53:06,2018-05-31 21:01:36,1,1.30,1,50,162,1,7.5,0.5,1.75,10.55,2018,5,31,3,20,sunny,6pm-8pm
902877,1,2018-05-04 19:49:32,2018-05-04 19:58:30,2,1.10,1,90,113,1,7.5,0.5,1.75,10.55,2018,5,4,4,19,rainy,6pm-8pm
902878,1,2018-05-06 08:21:10,2018-05-06 08:23:57,1,0.60,1,48,186,2,4.0,0.0,0.00,4.80,2018,5,6,6,8,sunny,6am-8am
902879,2,2018-05-14 21:14:01,2018-05-14 21:25:11,4,2.37,1,90,148,1,10.0,0.5,2.82,14.12,2018,5,14,0,21,snow,9pm-11pm
902880,2,2018-05-17 21:42:23,2018-05-17 22:00:50,1,2.88,1,161,236,1,14.0,0.5,3.06,18.36,2018,5,17,3,21,sunny,9pm-11pm
902881,1,2018-05-21 05:46:06,2018-05-21 05:48:36,2,0.70,1,100,230,1,4.5,0.5,1.00,6.80,2018,5,21,0,5,snow,3am-5am
902882,1,2018-05-29 07:29:00,2018-05-29 08:05:07,1,6.60,1,225,228,1,27.0,0.0,4.17,31.97,2018,5,29,1,7,overcast,6am-8am
902883,1,2018-05-24 09:33:23,2018-05-24 10:00:23,2,3.90,1,234,12,2,19.5,0.0,0.00,20.30,2018,5,24,3,9,sunny,9am-11am
902884,2,2018-05-31 07:26:07,2018-05-31 07:31:36,1,1.26,1,141,263,1,6.0,0.0,1.36,8.16,2018,5,31,3,7,sunny,6am-8am
902885,2,2018-05-08 20:07:50,2018-05-08 20:32:10,2,16.89,2,132,170,2,52.0,0.0,0.00,58.56,2018,5,8,1,20,overcast,6pm-8pm
902886,2,2018-05-09 22:51:03,2018-05-09 23:16:21,1,16.46,1,132,255,1,45.0,0.5,3.00,49.30,2018,5,9,2,22,overcast,9pm-11pm
902887,2,2018-05-01 14:32:36,2018-05-01 14:52:29,1,2.76,1,143,236,1,14.5,0.0,3.06,18.36,2018,5,1,1,14,sunny,12pm-2pm
902888,1,2018-05-17 22:10:08,2018-05-17 22:41:25,1,11.70,1,138,170,1,35.0,0.5,8.41,50.47,2018,5,17,3,22,sunny,9pm-11pm
902889,2,2018-05-19 13:55:19,2018-05-19 14:03:13,1,0.90,1,237,161,1,6.5,0.0,1.46,8.76,2018,5,19,5,13,sunny,12pm-2pm
902890,2,2018-05-07 19:34:07,2018-05-07 19:46:55,3,2.58,1,246,79,2,11.0,1.0,0.00,12.80,2018,5,7,0,19,snow,6pm-8pm
902891,1,2018-05-20 16:03:02,2018-05-20 16:19:51,1,3.00,1,231,164,2,13.0,0.0,0.00,13.80,2018,5,20,6,16,sunny,3pm-5pm
902892,2,2018-05-22 18:04:43,2018-05-22 18:12:00,1,0.92,1,179,7,2,6.5,1.0,0.00,8.30,2018,5,22,1,18,snow,6pm-8pm
902893,1,2018-05-02 09:42:23,2018-05-02 09:51:59,1,1.30,1,230,43,2,8.0,0.0,0.00,8.80,2018,5,2,2,9,snow,9am-11am
902894,2,2018-05-19 21:07:56,2018-05-19 21:16:17,6,1.58,1,263,229,1,8.0,0.5,2.00,11.30,2018,5,19,5,21,sunny,9pm-11pm
902895,2,2018-05-12 20:30:45,2018-05-12 21:12:34,4,7.63,1,137,36,2,30.5,0.5,0.00,31.80,2018,5,12,5,20,snow,6pm-8pm
902896,1,2018-05-18 07:52:42,2018-05-18 07:56:25,1,0.70,1,90,234,2,5.0,0.0,0.00,5.80,2018,5,18,4,7,sunny,6am-8am
902897,1,2018-05-30 08:14:31,2018-05-30 08:20:53,1,1.00,1,236,237,3,6.5,0.0,0.00,7.30,2018,5,30,2,8,overcast,6am-8am
902898,2,2018-05-12 22:19:05,2018-05-12 22:27:52,5,1.30,1,107,79,2,7.5,0.5,0.00,8.80,2018,5,12,5,22,snow,9pm-11pm
902899,1,2018-05-25 21:08:42,2018-05-25 21:14:18,4,1.10,1,88,231,2,6.0,0.5,0.00,7.30,2018,5,25,4,21,sunny,9pm-11pm
902900,2,2018-05-17 18:42:44,2018-05-17 18:52:10,1,1.56,1,238,142,1,8.0,1.0,1.96,11.76,2018,5,17,3,18,sunny,6pm-8pm
902901,2,2018-05-05 18:52:53,2018-05-05 19:03:06,1,1.05,1,90,158,2,8.0,0.0,0.00,8.80,2018,5,5,5,18,rainy,6pm-8pm
902902,1,2018-05-06 20:01:16,2018-05-06 20:20:30,1,4.00,1,68,140,1,15.5,0.5,2.00,18.80,2018,5,6,6,20,sunny,6pm-8pm

In [8]:
len(combined_csv)

2738708