In [7]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("yellow_tripdata_2015-05.csv")

In [21]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2015-05-05 23:37:40,2015-05-05 23:45:41,1,2.00,-74.001678,40.739311,1,N,-73.978294,40.752110,2,8.5,0.5,0.5,0.00,0.00,0.3,9.80
1,2,2015-05-05 23:37:40,2015-05-05 23:40:36,1,0.54,-73.930840,40.744789,1,N,-73.937515,40.749359,2,4.5,0.5,0.5,0.00,0.00,0.3,5.80
2,2,2015-05-05 23:37:40,2015-05-05 23:44:03,3,2.10,-74.001411,40.731087,1,N,-73.981674,40.758282,2,8.0,0.5,0.5,0.00,0.00,0.3,9.30
3,2,2015-05-05 23:37:40,2015-05-06 00:14:01,6,10.93,-73.970673,40.758560,1,N,-73.933762,40.670544,1,36.0,0.5,0.5,9.32,0.00,0.3,46.62
4,2,2015-05-05 23:37:40,2015-05-05 23:46:03,5,0.93,-73.986732,40.755878,1,N,-73.990959,40.749981,1,7.0,0.5,0.5,2.49,0.00,0.3,10.79
5,1,2015-05-05 23:37:41,2015-05-05 23:50:34,3,2.40,-73.989326,40.756599,1,N,-73.979584,40.735363,2,11.0,0.5,0.5,0.00,0.00,0.3,12.30
6,1,2015-05-05 23:37:42,2015-05-05 23:41:51,1,1.30,-73.955544,40.776722,1,N,-73.941338,40.788120,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
7,2,2015-05-05 23:37:42,2015-05-05 23:53:25,1,3.70,-73.992210,40.729187,1,N,-73.960396,40.775631,1,15.0,0.5,0.5,3.26,0.00,0.3,19.56
8,2,2015-05-05 23:37:42,2015-05-05 23:52:53,2,7.84,-73.987740,40.740860,1,N,-73.873169,40.723091,1,23.5,0.5,0.5,6.07,5.54,0.3,36.41
9,2,2015-05-05 23:37:42,2015-05-05 23:48:25,3,2.36,-73.987999,40.743996,1,N,-73.998528,40.717003,2,10.0,0.5,0.5,0.00,0.00,0.3,11.30
10,2,2015-05-05 23:37:42,2015-05-05 23:41:37,1,1.35,-73.971039,40.757938,1,N,-73.980652,40.742249,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
11,1,2015-05-05 23:37:43,2015-05-05 23:42:23,1,1.30,-73.978065,40.725159,1,N,-73.978920,40.713619,1,6.0,0.5,0.5,1.45,0.00,0.3,8.75
12,1,2015-05-05 23:37:43,2015-05-05 23:49:51,2,4.70,-73.976501,40.749886,1,N,-74.006165,40.707947,1,15.5,0.5,0.5,3.36,0.00,0.3,20.16
13,1,2015-05-05 23:37:43,2015-05-05 23:50:24,1,2.20,-73.957817,40.717800,1,N,-73.932007,40.706448,2,10.5,0.5,0.5,0.00,0.00,0.3,11.80
14,1,2015-05-05 23:37:43,2015-05-05 23:45:51,2,2.20,-73.968948,40.798847,1,N,-73.989784,40.775887,1,9.0,0.5,0.5,1.00,0.00,0.3,11.30
15,2,2015-05-05 23:37:43,2015-05-05 23:50:33,3,3.59,-73.988113,40.732143,1,N,-73.963524,40.774357,1,13.0,0.5,0.5,3.58,0.00,0.3,17.88
16,2,2015-05-05 23:37:43,2015-05-05 23:38:46,1,0.00,0.000000,0.000000,5,N,0.000000,0.000000,2,50.0,0.0,0.5,0.00,0.00,0.3,50.80
17,2,2015-05-05 23:37:43,2015-05-05 23:38:46,1,0.00,0.000000,0.000000,5,N,0.000000,0.000000,4,-50.0,0.0,-0.5,0.00,0.00,-0.3,-50.80
18,2,2015-05-05 23:37:43,2015-05-05 23:51:22,1,2.50,-73.971695,40.754551,1,N,-73.949577,40.785343,2,12.5,0.5,0.5,0.00,0.00,0.3,13.80
19,1,2015-05-05 23:37:44,2015-05-05 23:57:01,2,2.80,-73.988914,40.718971,1,N,-73.994186,40.703239,1,14.0,0.5,0.5,3.05,0.00,0.3,18.35
20,1,2015-05-05 23:37:44,2015-05-05 23:51:46,1,3.20,-73.989250,40.758499,1,N,-73.991066,40.727680,1,12.5,0.5,0.5,2.75,0.00,0.3,16.55
21,2,2015-05-05 23:37:44,2015-05-05 23:43:06,1,1.39,-73.952141,40.777485,1,N,-73.960373,40.761742,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
22,2,2015-05-24 15:38:34,2015-05-24 16:04:05,1,5.25,-73.994263,40.751228,1,N,-73.940079,40.797821,1,20.5,0.0,0.5,4.26,0.00,0.3,25.56
23,2,2015-05-24 15:38:34,2015-05-24 15:43:17,5,0.76,-73.990417,40.718861,1,N,-73.982658,40.723282,1,5.5,0.0,0.5,0.00,0.00,0.3,6.30
24,2,2015-05-24 15:38:34,2015-05-24 15:43:55,1,1.21,-73.939163,40.805420,1,N,-73.952652,40.791451,2,6.0,0.0,0.5,0.00,0.00,0.3,6.80
25,2,2015-05-24 15:38:34,2015-05-24 15:55:20,1,3.18,-73.954605,40.714050,1,N,-73.988518,40.696846,1,13.0,0.0,0.5,2.76,0.00,0.3,16.56
26,1,2015-05-24 15:38:35,2015-05-24 15:57:56,3,6.00,-74.004105,40.707306,1,N,-73.973122,40.764107,1,21.0,0.0,0.5,4.35,0.00,0.3,26.15
27,1,2015-05-24 15:38:35,2015-05-24 15:43:33,1,0.50,-73.991501,40.750019,1,N,-73.985870,40.750420,2,5.0,0.0,0.5,0.00,0.00,0.3,5.80
28,1,2015-05-24 15:38:35,2015-05-24 15:54:36,3,6.00,-74.013222,40.702339,1,N,-73.977341,40.757854,2,19.5,0.0,0.5,0.00,0.00,0.3,20.30
29,2,2015-05-24 15:38:35,2015-05-24 15:52:26,1,4.36,-74.005478,40.728294,1,N,-73.981430,40.780010,2,15.0,0.0,0.5,0.00,0.00,0.3,15.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13158232,1,2015-05-21 19:43:29,2015-05-21 19:53:00,2,1.70,-73.952271,40.772549,1,N,-73.979477,40.783985,2,8.5,1.0,0.5,0.00,0.00,0.3,10.30
13158233,1,2015-05-21 19:43:29,2015-05-21 20:07:29,1,1.50,-73.978920,40.761848,1,N,-73.985916,40.750126,1,14.5,1.0,0.5,3.25,0.00,0.3,19.55
13158234,1,2015-05-21 19:43:29,2015-05-21 19:56:39,1,1.90,-73.963631,40.777184,1,N,-73.983269,40.767529,1,10.5,0.5,0.5,2.95,0.00,0.3,14.75
13158235,2,2015-05-21 19:43:29,2015-05-21 20:03:44,6,2.90,-73.986389,40.753700,1,N,-73.994530,40.722172,1,14.5,1.0,0.5,3.26,0.00,0.3,19.56
13158236,2,2015-05-21 19:43:29,2015-05-21 19:45:39,1,0.37,-73.984909,40.727982,1,N,-73.988869,40.731380,2,3.5,1.0,0.5,0.00,0.00,0.3,5.30
13158237,1,2015-05-21 19:43:30,2015-05-21 19:57:57,1,2.60,-73.956238,40.767361,1,N,-73.972038,40.792301,2,12.0,1.0,0.5,0.00,0.00,0.3,13.80
13158238,1,2015-05-21 19:43:30,2015-05-21 19:47:42,1,0.80,-73.961433,40.774925,1,N,-73.968613,40.764729,1,5.5,1.0,0.5,2.15,0.00,0.3,9.45
13158239,1,2015-05-21 19:43:30,2015-05-21 20:00:29,1,2.10,-73.983795,40.737408,1,N,-73.978142,40.761890,2,12.5,1.0,0.5,0.00,0.00,0.3,14.30
13158240,1,2015-05-21 19:53:11,2015-05-21 19:59:33,1,1.20,-73.972023,40.765663,1,N,-73.962212,40.775425,1,6.5,1.0,0.5,1.65,0.00,0.3,9.95
13158241,1,2015-05-21 19:53:11,2015-05-21 19:57:37,1,1.10,-73.961342,40.760700,1,N,-73.955513,40.772861,1,5.5,1.0,0.5,1.45,0.00,0.3,8.75
13158242,1,2015-05-21 19:53:11,2015-05-21 20:05:57,3,2.20,0.000000,0.000000,1,N,0.000000,0.000000,1,11.0,1.0,0.5,2.50,0.00,0.3,15.30
13158243,1,2015-05-21 19:53:11,2015-05-21 19:55:31,1,0.30,-73.948189,40.774578,1,N,-73.952759,40.772575,2,4.0,1.0,0.5,0.00,0.00,0.3,5.80
13158244,1,2015-05-21 19:53:11,2015-05-21 19:56:29,1,0.70,-73.962509,40.767265,1,N,-73.956001,40.776192,1,4.5,1.0,0.5,1.26,0.00,0.3,7.56
13158245,1,2015-05-21 19:53:11,2015-05-21 19:56:34,1,0.70,-73.975693,40.751766,1,N,-73.980423,40.743305,2,4.5,1.0,0.5,0.00,0.00,0.3,6.30
13158246,1,2015-05-21 19:53:11,2015-05-21 20:16:20,1,5.90,-73.990608,40.738773,1,N,-73.967453,40.793758,1,21.5,0.5,0.5,4.55,0.00,0.3,27.35
13158247,2,2015-05-21 19:53:11,2015-05-21 20:19:59,2,13.82,-73.981468,40.732815,1,N,-73.898430,40.898487,1,38.0,1.0,0.5,9.95,0.00,0.3,49.75
13158248,2,2015-05-21 19:53:11,2015-05-21 20:02:51,1,0.95,-73.972832,40.744286,1,N,-73.984718,40.751293,1,7.5,1.0,0.5,1.86,0.00,0.3,11.16
13158249,2,2015-05-21 19:53:11,2015-05-21 20:05:18,1,2.23,-73.986984,40.770714,1,N,-73.967560,40.792850,1,10.5,1.0,0.5,2.20,0.00,0.3,14.50
13158250,2,2015-05-21 19:53:11,2015-05-21 20:10:16,1,1.69,-73.991562,40.737652,1,N,-74.001915,40.732231,1,11.5,1.0,0.5,1.00,0.00,0.3,14.30
13158251,2,2015-05-21 19:53:11,2015-05-21 19:58:13,1,1.57,-74.008560,40.732761,1,N,-74.015984,40.715134,1,6.5,1.0,0.5,1.50,0.00,0.3,9.80
13158252,1,2015-05-21 19:53:12,2015-05-21 19:59:32,1,0.70,-73.985313,40.759525,1,N,-73.996689,40.763180,2,6.0,1.0,0.5,0.00,0.00,0.3,7.80
13158253,1,2015-05-21 19:53:12,2015-05-21 19:56:39,1,0.50,-73.984077,40.725655,1,N,-73.985039,40.720371,2,4.5,1.0,0.5,0.00,0.00,0.3,6.30
13158254,1,2015-05-21 19:53:12,2015-05-21 20:20:31,3,2.60,-73.980019,40.765453,1,N,-73.990913,40.733913,1,17.5,1.0,0.5,2.00,0.00,0.3,21.30
13158255,1,2015-05-21 19:53:12,2015-05-21 20:05:40,1,2.90,-74.014488,40.703331,1,N,-74.007217,40.741299,1,12.5,0.5,0.5,2.75,0.00,0.3,16.55
13158256,2,2015-05-21 19:53:12,2015-05-21 20:07:01,2,2.10,-73.974403,40.736832,1,N,-73.984604,40.728783,1,11.0,1.0,0.5,2.56,0.00,0.3,15.36
13158257,2,2015-05-21 19:53:12,2015-05-21 20:09:48,1,3.42,-74.006157,40.714066,1,N,-73.983795,40.751007,1,14.0,1.0,0.5,3.16,0.00,0.3,18.96
13158258,1,2015-05-21 19:53:13,2015-05-21 20:00:59,1,0.90,-73.983887,40.760014,1,N,-73.973198,40.764046,2,6.5,1.0,0.5,0.00,0.00,0.3,8.30
13158259,2,2015-05-21 19:53:13,2015-05-21 19:58:08,1,0.90,-73.981049,40.741798,1,N,-73.973709,40.752155,1,5.5,1.0,0.5,1.00,0.00,0.3,8.30
13158260,2,2015-05-21 19:53:13,2015-05-21 20:29:38,1,9.24,-73.976608,40.759380,1,N,-74.014328,40.676208,1,30.5,1.0,0.5,0.00,0.00,0.3,32.30
13158261,2,2015-05-21 19:53:13,2015-05-21 20:16:28,1,2.37,-73.989906,40.751919,1,N,-73.999336,40.723236,1,16.0,1.0,0.5,1.00,0.00,0.3,18.80

In [23]:
df_filter = df[(df.dropoff_longitude != 0) & (df.dropoff_latitude != 0)]

In [24]:
sample = df_filter[['tpep_dropoff_datetime', 'passenger_count', 'trip_distance',
             'dropoff_longitude','dropoff_latitude', 'tip_amount', 'payment_type']].sample(n=200000)

In [25]:
sample
#sample.to_csv('sample2w-2015-12.csv')

,tpep_dropoff_datetime,passenger_count,trip_distance,dropoff_longitude,dropoff_latitude,tip_amount,payment_type
6560440,2015-05-30 12:11:00,1,2.27,-73.980186,40.665428,0.00,2
1679961,2015-05-15 11:37:23,1,1.43,-73.986320,40.760704,0.00,2
2570618,2015-05-21 01:50:00,1,1.00,-73.925400,40.742847,0.00,2
8832380,2015-05-11 08:15:41,3,1.07,-73.958740,40.772373,2.56,1
9097190,2015-05-16 11:26:23,1,0.70,-73.958862,40.768959,1.00,1
4209476,2015-05-22 06:11:44,1,0.40,-73.969460,40.760872,0.00,2
6222191,2015-05-03 15:01:09,2,2.10,-73.982887,40.722858,1.85,1
5299169,2015-05-20 11:23:41,1,1.90,-73.981178,40.773746,0.00,2
6547665,2015-05-09 23:38:55,1,29.50,-73.523041,40.863113,25.00,1
530962,2015-05-24 18:06:06,1,0.71,-73.989830,40.756680,0.00,2
3283397,2015-05-14 09:59:57,1,1.40,-73.969231,40.753342,4.10,1
10121260,2015-05-06 05:35:24,1,0.83,-73.975174,40.741554,1.16,1
5193263,2015-05-27 00:35:02,1,21.75,-73.990433,40.672249,17.50,1
11935040,2015-05-20 19:57:45,1,1.20,-73.979240,40.727825,1.00,1
3948123,2015-05-10 13:22:45,2,2.20,-73.994217,40.756611,2.00,1
11611433,2015-05-31 21:02:27,6,2.81,-73.973618,40.752136,3.45,1
11081991,2015-05-10 07:39:15,1,1.10,-73.968102,40.765415,1.45,1
1920335,2015-05-02 21:42:30,1,1.61,-73.978279,40.745716,2.00,1
9596998,2015-05-16 18:43:57,1,2.40,-73.974106,40.750076,0.00,3
4784501,2015-05-06 00:54:41,1,0.64,-74.001923,40.739868,0.00,2
6938318,2015-05-20 17:34:48,3,2.10,-73.939812,40.794399,0.00,2
3818179,2015-05-28 10:43:12,1,0.54,-74.000977,40.725594,0.96,1
8858818,2015-05-15 20:22:18,1,4.44,-73.947678,40.803936,1.00,1
3812893,2015-05-30 17:56:18,1,3.80,-73.988342,40.769772,0.00,2
10206275,2015-05-03 19:26:31,6,0.49,-73.989944,40.732491,0.00,2
11920109,2015-05-02 16:13:14,1,2.11,-73.955353,40.772961,0.00,2
363956,2015-05-28 19:01:01,1,2.16,-73.989342,40.745197,2.26,1
6288804,2015-05-10 11:54:05,1,0.75,-73.999229,40.728279,0.50,1
8714709,2015-05-25 04:15:05,2,2.00,-73.988762,40.727020,0.00,2
4194318,2015-05-03 00:46:48,1,0.80,-73.987778,40.732399,1.36,1
...,...,...,...,...,...,...,...
2078480,2015-05-06 04:44:58,1,11.04,-73.864761,40.770290,7.47,1
10426026,2015-05-09 12:39:52,1,5.30,-73.982513,40.723160,0.00,2
8284311,2015-05-02 15:19:36,1,4.06,-73.963043,40.714447,0.00,2
981731,2015-05-14 22:27:22,1,0.89,-73.989998,40.728790,0.00,2
3786837,2015-05-09 02:13:29,1,1.94,-73.992111,40.749191,0.00,2
8626639,2015-05-07 18:11:19,1,2.40,-73.977577,40.779194,0.00,2
8444551,2015-05-09 19:13:58,1,1.90,-73.982346,40.757565,0.00,2
3777184,2015-05-28 19:49:48,1,1.37,-73.996117,40.732128,1.76,1
8597867,2015-05-14 23:13:12,1,1.78,-73.975807,40.734760,0.00,2
6697048,2015-05-19 18:14:20,1,9.74,-73.870720,40.773796,8.47,1
968518,2015-05-02 13:22:52,1,0.92,-73.985344,40.763237,1.66,1
10025115,2015-05-24 20:03:59,1,2.10,-73.973709,40.748043,1.95,1
1895580,2015-05-15 23:48:49,2,4.43,-73.975044,40.761848,0.00,2
9545462,2015-05-09 19:17:07,1,0.70,-73.972832,40.749100,1.00,1
9446053,2015-05-18 16:08:19,1,1.40,-73.954063,40.806419,0.00,2
76735,2015-05-15 19:52:39,1,1.06,-73.982353,40.745457,2.06,1
8604744,2015-05-03 00:23:50,2,3.58,-73.944595,40.779503,2.00,1
12364388,2015-05-22 21:16:24,1,1.60,-73.966095,40.774178,0.00,2
11630234,2015-05-30 05:40:47,1,5.00,-74.012375,40.701550,0.00,2
12531679,2015-05-30 01:49:52,2,8.20,-73.869377,40.733479,6.45,1
103508,2015-05-30 21:59:44,2,2.30,-73.984367,40.732075,2.00,1
1572512,2015-05-04 13:02:10,2,2.14,-73.959061,40.780609,0.00,2
12914911,2015-05-22 00:11:37,5,2.38,-73.969467,40.785469,2.46,1
2508643,2015-05-07 10:35:40,1,1.96,-73.951462,40.782768,2.16,1
12659298,2015-05-12 12:42:23,1,0.80,-73.970505,40.764355,2.35,1
8520404,2015-05-29 21:14:30,1,3.30,-73.983086,40.756145,0.00,2
12014495,2015-05-17 00:52:07,3,3.80,-73.982353,40.743305,0.00,2
7382792,2015-05-18 19:25:26,3,1.24,-73.977425,40.774357,0.00,2
6340031,2015-05-10 08:15:09,1,3.98,-73.996407,40.762428,0.00,2
8061676,2015-05-20 21:46:52,1,1.37,-73.981743,40.724339,2.26,1